name: CI

on:
  push:
  pull_request:

env:
  DATABASE_URL: "sqlite:///tmp/data.db"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install sqlx-cli
        run: cargo install sqlx-cli;

      - name: Setup auth database
        run: |
          cargo install sqlx-cli;
          sqlx database setup --source auth/server/migrations;

      - name: Run Tests
        run: cargo test --workspace --all-features --no-fail-fast -- --nocapture
